services:
  postgres:
    container_name: postgres
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/code/collected_static
      - media:/code/media
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    volumes:
      - static:/static
    command: >
      sh -c "
      mkdir -p /static &&
      cp -r /app/build/static/* /static/ &&
      cp /app/build/index.html /static/index.html
      "

  gateway:
    container_name: gateway
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    # порт специально стоит 9003, на 80, 81 и 443 развернут nginx proxy manager, 9000 и 9001 заняты portainer, 9002 для локального запуска, 9003 для автоматического
    # поэтому возможности на стандартных портах для http/https запуститься возможности нет, в требованиях нет обязательного использования 80 порта
    ports:
      - "9003:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media: